### PR TITLE
WIP Python 3

### PR DESCRIPTION
**Pull request by mancellin**
**Done**: Used 2to3 to convert the code to Python 3.

The code should still be compatible with Python 2 (modulo https://github.com/LHEEA/meshmagick/issues/11).
If it is not required to keep Python 2 compatibility, a lot of cleanup could be done (for instance, inheritance of `object` in class declarations).

**Ignored**: sphinx and content of the documentation.

**Broken**: `conda` recipe and current `.travis.yml`.
With [a simpler `.travis.yml`](https://raw.githubusercontent.com/mancellin/meshmagick/mini_travis/.travis.yml), it [passes the tests](https://travis-ci.org/mancellin/meshmagick/builds/578804092) (modulo https://github.com/LHEEA/meshmagick/issues/11).

### CODE REVIEW

**Comment by mancellin** [comment]
@frongere Do you plan to keep Python 2 compatibility? I guess not since one of your latest commit seems to work only on Python 3 (cf https://github.com/LHEEA/meshmagick/issues/11).

**Comment by frongere** [comment]
Hi Matthieu,
Sorry for the late integration and thank you for your work !
Your pull request has been merged into the master branch and meshmagick has now the version 2.0 !
François.

**Comment by mancellin** [comment]
Thanks.
Actually, the point of my last message was to ask whether I should add to the PR some Python-3-only commits I have on my fork. Is your plan for meshmagick to require Python 3.6 or 3.7 from now on?

**Comment by frongere** [comment]
Hi,
I must admit that it would be nice to keep compatibility with Python 2.7 for those who still rely on that version...
What are the features added by your Python-3 only piece of code ?

**Comment by mancellin** [comment]
Nothing much. I was mostly thinking of cleaning up some Python 2 idioms.

Beside that, the code from Meshmagick that I've included in Capytaine has slightly evolved in its own direction, but in the long run it could be nice to try to merge some changes back in Meshmagick. It would avoid maintaining the same code in two repositories and a few things like the [geometry module](https://github.com/mancellin/capytaine/blob/master/capytaine/meshes/geometry.py) could be nice to have in Meshmagick. I guess it could be made compatible with Python 2 but I'm not sure it is worth the trouble.

**Pull request merged**
